name: Deploy to Koyeb

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
     uses: GY-CODING/.github/.github/workflows/koyeb-deploy.yml@master
     secrets: inherit

# For the workflow to know which service to deploy, the repository should have the following secrets.
# - KOYEB_EMAIL
# - KOYEB_PASSWORD
# - KOYEB_SERVICE_ID